from enum import Enum
from typing import Optional

from pydantic import BaseModel


class Severity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ReviewCategory(str, Enum):
    QUALITY = "Quality"
    SECURITY = "Security"
    STYLE = "Style"
    ARCHITECTURE = "Architecture"


class ReviewFinding(BaseModel):
    """
    Represents a single finding generated by a review agent.
    """

    file_path: str
    line_number: int

    severity: Severity
    category: ReviewCategory

    title: str
    message: str

    suggestion: Optional[str] = None